name: CI
on:
  pull_request:
    branches:
      - main
      - next
jobs:
  check:
    name: Check stuff
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Install dependencies
        run: pnpm install
      - name: Test Library
        run: pnpm test:ci
      - name: Build Library
        run: pnpm build
